// This is the rclone build script. It can build rclone binaries for any target
// architecture on any target architecture.

def buildTag = 'v1.75.0'
ext.ndkVersion = '27.2.12479018'

import java.nio.file.Paths
import java.nio.file.Files

def configureNdk() {
    def osName = System.properties['os.name'].toLowerCase()
    def osArch = System.properties['os.arch']

    def os = ''
    if (osName.contains('windows')) {
        os = "windows-x86_64"
    } else if (osName.contains("linux")) {
        os = "linux-x86_64"
    } else if (osName.contains('mac')) {
        os = "darwin-x86_64"
    } else {
        throw new GradleException("OS=${osName}/ARCH=${osArch} not supported")
    }

    def androidNdkHome = System.getenv('ANDROID_NDK_HOME')
    def androidHome = System.getenv('ANDROID_HOME')
    def ndkBasePath

    if (androidHome != null) {
        def canonicalPath = Paths.get(androidHome, 'ndk', ext.ndkVersion)
        def bundlePath = Paths.get(androidHome, 'ndk-bundle')
        if (Files.exists(canonicalPath)) {
            ndkBasePath = canonicalPath
        } else if (Files.exists(bundlePath)) {
            ndkBasePath = bundlePath
        }
    } else if (androidNdkHome != null) {
        ndkBasePath = Paths.get(androidNdkHome)
    }

    if (ndkBasePath == null) {
        println("NDK ${ext.ndkVersion} not found - skipping native binary compilation steps")
        return null
    }

    return ndkBasePath.resolve(Paths.get('toolchains', 'llvm', 'prebuilt', os, 'bin'))
}

def repository = 'github.com/rclone/rclone'
def repositoryRef = repository + '@' + buildTag
def ldflags = "-X github.com/rclone/rclone/fs.Version=${buildTag}-rcx"
def goPath = Paths.get(projectDir.absolutePath, 'gopath').toAbsolutePath().toString()
def appLibPath = Paths.get(projectDir.absolutePath, '../app/lib').toAbsolutePath().toString()
def ndkPrefix = configureNdk()

task fetchRclone(type: Exec) {
    enabled = (ndkPrefix != null)
    mkdir goPath
    environment 'GOPATH', goPath
    commandLine 'go', 'install', "${repositoryRef}"
}

task cleanNative {
    doLast {
        delete "${appLibPath}/armeabi-v7a/librclone.so"
        delete "${appLibPath}/arm64-v8a/librclone.so"
        delete "${appLibPath}/x86/librclone.so"
        delete "${appLibPath}/x86_64/librclone.so"
    }
}

task buildArm(type: Exec) {
    enabled = (ndkPrefix != null)
    dependsOn fetchRclone
    environment 'GOPATH', goPath
    def crossCompiler = ndkPrefix != null ? ndkPrefix.resolve('armv7a-linux-androideabi21-clang') : ''
    environment 'CC', crossCompiler
    environment 'CC_FOR_TARGET', crossCompiler
    environment 'GOOS', 'android'
    environment 'GOARCH', 'arm'
    environment 'GOARM', '7'
    environment 'CGO_ENABLED', '1'
    environment 'CGO_LDFLAGS', "-fuse-ld=lld -s -Wl,-z,max-page-size=16384"
    workingDir Paths.get(goPath, "pkg/mod/${repositoryRef}".split('/'))
    def artifactTarget = "${appLibPath}/armeabi-v7a/librclone.so"
    commandLine 'go', 'build', '-v', '-tags', 'android noselfupdate', '-trimpath', '-ldflags', ldflags, '-o', artifactTarget, '.'
}

task buildArm64(type: Exec) {
    enabled = (ndkPrefix != null)
    dependsOn fetchRclone
    environment 'GOPATH', goPath
    def crossCompiler = ndkPrefix != null ? ndkPrefix.resolve('aarch64-linux-android21-clang') : ''
    environment 'CC', crossCompiler
    environment 'CC_FOR_TARGET', crossCompiler
    environment 'GOOS', 'android'
    environment 'GOARCH', 'arm64'
    environment 'CGO_ENABLED', '1'
    environment 'CGO_LDFLAGS', "-fuse-ld=lld -s -Wl,-z,max-page-size=16384"
    workingDir Paths.get(goPath, "pkg/mod/${repositoryRef}".split('/'))
    def artifactTarget = "${appLibPath}/arm64-v8a/librclone.so"
    commandLine 'go', 'build', '-v', '-tags', 'android noselfupdate', '-trimpath', '-ldflags', ldflags, '-o', artifactTarget, '.'
}

task buildx86(type: Exec) {
    enabled = (ndkPrefix != null)
    dependsOn fetchRclone
    environment 'GOPATH', goPath
    def crossCompiler = ndkPrefix != null ? ndkPrefix.resolve('i686-linux-android21-clang') : ''
    environment 'CC', crossCompiler
    environment 'CC_FOR_TARGET', crossCompiler
    environment 'GOOS', 'android'
    environment 'GOARCH', '386'
    environment 'CGO_ENABLED', '1'
    environment 'CGO_LDFLAGS', "-fuse-ld=lld -s -Wl,-z,max-page-size=16384"
    workingDir Paths.get(goPath, "pkg/mod/${repositoryRef}".split('/'))
    def artifactTarget = "${appLibPath}/x86/librclone.so"
    commandLine 'go', 'build', '-v', '-tags', 'android noselfupdate', '-trimpath', '-ldflags', ldflags, '-o', artifactTarget, '.'
}

task buildx64(type: Exec) {
    enabled = (ndkPrefix != null)
    dependsOn fetchRclone
    environment 'GOPATH', goPath
    def crossCompiler = ndkPrefix != null ? ndkPrefix.resolve('x86_64-linux-android21-clang') : ''
    environment 'CC', crossCompiler
    environment 'CC_FOR_TARGET', crossCompiler
    environment 'GOOS', 'android'
    environment 'GOARCH', 'amd64'
    environment 'CGO_ENABLED', '1'
    environment 'CGO_LDFLAGS', "-fuse-ld=lld -s -Wl,-z,max-page-size=16384"
    workingDir Paths.get(goPath, "pkg/mod/${repositoryRef}".split('/'))
    def artifactTarget = "${appLibPath}/x86_64/librclone.so"
    commandLine 'go', 'build', '-v', '-tags', 'android noselfupdate', '-trimpath', '-ldflags', ldflags, '-o', artifactTarget, '.'
}

task buildNative {
    dependsOn fetchRclone
    dependsOn buildArm
    dependsOn buildArm64
    dependsOn buildx86
    dependsOn buildx64
}

buildNative.mustRunAfter(buildArm, buildArm64, buildx86, buildx64)
